apiVersion: v1
kind: Secret
metadata:
  # name: MongoDB-Secret # The Secret "MongoDB-Secret" is invalid: metadata.name: Invalid value: "MongoDB-Secret": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
# echo -n 'bddghfjfhj' | base64
